
spring:
  redis:
#    host: localhost
#    port: 6379
#    password: pwd
#    sentinel:
#      master: my_master
     nodes: localhost:6379,localhost:6381,localhost:6383
     lettuce:
       pool:
         max-active: 10
         max-idle: 8
         min-idle: 5
  cache:
    type: redis
    cache-names:
      - user
      - order
    redis:
      time-to-live: 86400000
debug: true
