# ====================================
# rabbitmq
# ====================================
spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    virtual-host: my_vhost
    listener:
      simple:
        acknowledge-mode: auto
      direct:
        acknowledge-mode: auto
#    publisher-confirms: true
#    publisher-confirm-type: correlated
server:
  port: 8080
